# base svd model path
base_model_path: models/stable_video_diffusion

# checkpoint path
ckpt_path: models/MimicMotion/MimicMotion_1-1.pth

test_case:
  - video_pose_dir: data/mimicmotion_test/poses
    ref_image_path: data/mimicmotion_test/example_image.png
    ref_pose_path: data/mimicmotion_test/example_image_pose.json
    output_path: outputs/mimicmotion_test/mimicmotion.mp4
    num_frames: 56
    resolution: 576
    frames_overlap: 6
    num_inference_steps: 25
    noise_aug_strength: 0
    guidance_scale: 2.0
    sample_stride: 2
    fps: 30
    seed: 42