# base svd model path
base_model_path: models/stable_video_diffusion

# checkpoint path
ckpt_path: models/MimicMotion/MimicMotion_1-1.pth

test_case:
  - ref_video_path: third_party/MimicMotion/assets/example_data/videos/pose1.mp4
    ref_image_path: third_party/MimicMotion/assets/example_data/images/demo1.jpg
    num_frames: 72
    resolution: 576
    frames_overlap: 6
    num_inference_steps: 25
    noise_aug_strength: 0
    guidance_scale: 2.0
    sample_stride: 2
    fps: 15
    seed: 42